name: CI/CD
on:
  push:
    branches:
      - gcr
jobs:
  docker:
    runs-on: ubuntu-latest
    needs: tests
    name: Build and Publish docker image
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 # https://github.com/marketplace/actions/docker-login#github-container-registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: ./HelloWorldHttp/Dockerfile
          push: true
          tags: |
            chneau/testing-github-actions/test-image:latest
