name: CI/CD
on:
  push:
    branches:
      - master
    tags:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v1
      - run: |
          dotnet restore
          dotnet build
          dotnet test
  docker:
    runs-on: ubuntu-latest
    needs: tests
    name: Build and Publish docker image
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: testingchneau/testing-github-actions
          tag_with_ref: true
          tag_with_sha: true
